# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false


os:
 - linux
 - osx


r:
 - 3.3
 - release
 - devel

after_success:
 - Rscript -e 'covr::codecov(type = "all")'
